# azure pipelines build and test pymapdl

variables:
  ALLOW_PLOTTING: true
  package_name: ansys-dpf-core
  SHELLOPTS: 'errexit:pipefail'

trigger:
  branches:
    include:
    - '*'
    exclude:
    - gh-pages
  tags:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'
    exclude:
    - '*no-ci*'

jobs:
- job: TestPlotImage
  variables:
    python.version: '3.8'
    PYANSYS_OFF_SCREEN: True
    DPF_PORT: 32772
    GH_DOC_BRANCH: 'gh-pages'
  pool:
    vmImage: 'windows-2019'

  steps:  
    - template: templates\prepare-environment-windows.yml    
   
    - script: |
          import pyvista
          pyvista.Sphere().plot(screenshot="tmp.png", off_screen=True)
      displayName: PyVista Plot
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish screenshot artifact'
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)\tmp.png'
        ArtifactName: tmp
      enabled: true
          
    - template: templates\kill-servers-windows.yml
