name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8   
      
      - name: Test plot image
        run: |
          pip install -r requirements_docs.txt
          python .ci\test_plot_image.py

      - uses: actions/upload-artifact@v2
        with:
          name: tmp
          path: .ci\tmp.png