name: Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2019

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8

      - name: Install ansys-dpf-core
        run: |
          pip install -r requirements_build.txt
          python setup.py bdist_wheel
          FOR /F %%a in ('dir /s/b dist\*.whl') do SET WHEELPATH=%%a
          ECHO %WHEELPATH% 
          pip install %WHEELPATH%
          cd tests
          python -c "from ansys.dpf import core; print(core.Report(gpu=False))"           
      
      - name: Test plot image
        run: |
          pip install -r requirements_docs.txt
          python .ci\test_plot_image.py

      - uses: actions/upload-artifact@v2
        with:
          name: tmp
          path: .ci\tmp.png